emojis:
  heart:
    emoticon: '<3'
    emoji: '&c‚ù§'
  star:
    emoticon: ':star:'
    emoji: '&6‚úÆ'
  yes:
    emoticon: ':yes:'
    emoji: '&a‚úî'
  no:
    emoticon: ':no:'
    emoji: '&c‚úñ'
  java:
    emoticon: ':java:'
    emoji: '&b‚òï'
  arrow:
    emoticon: ':arrow:'
    emoji: '&e‚ûú'
  shrug:
    emoticon: ':shrug:'
    emoji: '&e¬Ø\\_(„ÉÑ)_/¬Ø'
  tableflip:
    emoticon: ':tableflip:'
    emoji: '&c(‚ïØ¬∞‚ñ°¬∞Ôºâ‚ïØ&r&fÔ∏µ&r&7 ‚îª‚îÅ‚îª'
  wave:
    emoticon: 'o/'
    emoji: '&d( Ôæü‚ó°Ôæü)/'
  123:
    emoticon: ':123:'
    emoji: '&a1&r&e2&r&c3'
  totem:
    emoticon: ':totem:'
    emoji: '&b‚òâ&r&e_&r&b‚òâ'
  typing:
    emoticon: ':typing:'
    emoji: '&e‚úé&r&6...'
  maths:
    emoticon: ':maths:'
    emoji: '&a‚àö&r&e&l(&r&aœÄ&r&a&l+x&r&e&l)&r&a&l=&r&c&lL'
  snail:
    emoticon: ':snail:'
    emoji: '&e@&r&a''&r&e-&r&a'''
  thinking:
    emoticon: ':thinking:'
    emoji: '&6(&r&a0&r&6.&r&ao&r&c?&r&6)'
  gimme:
    emoticon: ':gimme:'
    emoji: '&b‡ºº„Å§‚óï_‚óï‡ºΩ„Å§'
  wizard:
    emoticon: ':wizard:'
    emoji: '&e(&r&b''&r&e-&r&b''&r&e)‚äÉ&r&c‚îÅ&r&d‚òÜÔæü.*ÔΩ•ÔΩ°Ôæü'
  pvp:
    emoticon: ':pvp:'
    emoji: '&e‚öî'
  peace:
    emoticon: ':peace:'
    emoji: '&a‚úå'
  oof:
    emoticon: ':oof:'
    emoji: '&c&lOOF'
  puffer:
    emoticon: ':puffer:'
    emoji: '&e&l<(''O'')>'
  snow:
    emoticon: ':snow:'
    emoji: '&b‚òÉ'
  yey:
    emoticon: ':yey:'
    emoji: '&a„ÉΩ (‚óï‚ó°‚óï) Ôæâ'
  sloth:
    emoticon: ':sloth:'
    emoji: '&6(&r&8„Éª&r&6‚äù&r&8„Éª&r&6)'
  hey:
    emoticon: 'h/'
    emoji: '&e„ÉΩ(^‚óá^*)/'
  cat:
    emoticon: ':cat:'
    emoji: '&e= &r&bÔºæ‚óè ‚ãè ‚óèÔºæ&r&e ='
  dab:
    emoticon: ':dab:'
    emoji: '&d<&r&eo&r&d/'
  dog:
    emoticon: ':dog:'
    emoji: '&6(·µî·¥•·µî)'
  joy:
    emoticon: [ '^_^', '^-^' ]
    emoji: '&a$1'
  dj:
    emoticon: ':dj:'
    emoji: '&9„ÉΩ&r&5(&r&d‚åê&r&c‚ñ†&r&6_&r&e‚ñ†&r&b)&r&3„Éé&r&9‚ô¨'
  cute:
    emoticon: ':cute:'
    emoji: '&e(&r&a‚úø&r&e‚ó†‚Äø‚ó†)'
  facepalm:
    emoticon: ':facepalm:'
    emoji: '&6(&eÔºç‚Ä∏·Éö&6)'
  skull:
    emoticon: ':skull:'
    emoji: '&7‚ò†'
  uwu:
    emoticon: 'UwU'
    emoji: '&d$1'
  owo:
    emoticon: 'OwO'
    emoji: '&b$1'
  happy:
    emoticon: ':)'
    emoji: '‚ò∫'
  sad:
    emoticon: ':('
    emoji: '‚òπ'
  sword:
    emoticon: ':sword:'
    emoji: 'üó°'
  bow:
    emoticon: ':bow:'
    emoji: 'üèπ'
  trident:
    emoticon: ':trident:'
    emoji: 'üî±'
  potion:
    emoticon: ':potion:'
    emoji: 'üß™'
  splash_potion:
    emoticon: ':splash_potion:'
    emoji: '‚öó'
  fishing_rod:
    emoticon: ':fishing_rod:'
    emoji: '‚öó'
  shield:
    emoticon: ':shield:'
    emoji: 'üõ°'
  axe:
    emoticon: ':axe:'
    emoji: '‚öó'